### ISSUE TITLE
Exclude PHPUnit / Rector from psr-4

### ISSUE THREAD

**Issue by fliespl** [systemsdk/docker-nginx-php-symfony#21]
According to author it does not follow psr-4 so should it be defined in composer.json?

https://github.com/sebastianbergmann/phpunit/issues/4168

Rendered warnings when used with ""optimize-autoloader": true," config.

**Comment by dimadeush** [comment]
Please do not use optimize-autoloader for the dev environment, see recommendations here - https://getcomposer.org/doc/articles/autoloader-optimization.md#autoloader-optimization and pay your attention to the notes. Regarding classmap you can try but I'm not sure that it will help in your case.
